- job:
    name: tricircle-functional
    parent: legacy-dsvm-base
    run: playbooks/tricircle-dsvm-functional/run.yaml
    post-run: playbooks/tricircle-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/tricircle

- job:
    name: tricircle-multiregion
    parent: legacy-dsvm-base-multinode
    run: playbooks/tricircle-dsvm-multiregion/run.yaml
    post-run: playbooks/tricircle-dsvm-multiregion/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/networking-sfc
      - openstack/tricircle
    nodeset: legacy-ubuntu-xenial-2-node

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-cover
        - tricircle-functional
        - tricircle-multiregion
    gate:
      jobs:
        - openstack-tox-cover
        - tricircle-functional
        - tricircle-multiregion
